# @package agent
_target_: agent.ddpg.DDPGAgent
name: ddpg
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}

use_tb: ${use_tb}
use_wandb: ${use_wandb}

init_actor: True
init_critic: true
init_critic_mode: 'only_trunk'
update_encoder: ${update_encoder}
grad_critic_params: null
optional_inits_args: null

lr: 1e-4
actor_lr: ${agent.lr}
critic_lr: ${agent.lr}
critic_target_tau: 0.01
update_every_steps: 2
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
