# @package agent
_target_: agent.np_ddpg.NonParamDDPGAgent
_recursive_: False
name: gp_ddpg

reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}

use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later

lr: 1e-3
critic_target_tau: 0.01
update_every_steps: 2

hidden_dim: 256
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024 # 256 for pixels
init_critic: true
update_encoder: ${update_encoder}

twin_q: True

mc_buffer_cfg:
  capacity: 20000
  discount: ${discount}

# critic attributes (TODO future: make critic_cfg)
memory_overwrite: "none"

value_head_cfg:
  _target_: modules.gaussian_process.IIDGaussianNoiseGP
  _recursive_: False
  key_dim: ${agent.hidden_dim}
  value_dim: 1
  keys_grad: True
  values_grad: True
  capacity: 256
  noise_var: 1.0
  kernel_fn_cfg:
    _target_: modules.gaussian_process.SEKernel
    _recursive_: False
    lengthscale: 3.0
    train_lengthscale: False
