# @package agent
_target_: agent.np_proto.NonParamValueProtoAgent
_recursive_: False
name: np_value_proto

reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}

use_tb: ${use_tb}
use_wandb: ${use_wandb}

# Loading and fine-tuning
init_actor: true
init_critic: true
init_critic_mode: 'only_trunk'
update_encoder: ${update_encoder}
grad_critic_params: null
optional_inits_args: null

base_optim_cfg:
  _target_: torch.optim.Adam
  lr: 1e-4
actor_optim_cfg:
  _target_: ${agent.base_optim_cfg._target_}
  lr: ${agent.base_optim_cfg.lr}
critic_optim_cfg:
  _target_: ${agent.base_optim_cfg._target_}
  lr: ${agent.base_optim_cfg.lr}

critic_target_tau: 0.01
update_every_steps: 2
twin_q: True
num_expl_steps: ??? # to be specified later

hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024

pred_dim: 128
proj_dim: 512
num_protos: 512
tau: 0.1
topk: 3
queue_size: 2048
encoder_target_tau: 0.05

actor_cfg:
  _target_: agent.np_proto.NonParametricProtoActor
  _recursive_: False
  obs_type: ???
  obs_dim: ???
  action_dim: ???
  device: ${device}
  feature_dim: ${agent.feature_dim}
  hidden_dim: ${agent.hidden_dim}
  key_dim: ${agent.pred_dim}
  snd_kwargs:
    capacity: ${agent.num_protos}
    key_dim: ${agent.pred_dim}  # prototype dimensions
    value_dim: ???
    temperature: 0.1
    keys_grad: False
    values_grad: True
    temperature_grad: False
    values_init: null
    device: ${device}
    score_fn_cfg:
      _target_: modules.neural_dictionary.CosineSimilaritySF
      _recursive_: False

critic_cfg:
  _target_: agent.ddpg.Critic
  _recursive_: False
  obs_type: ???
  obs_dim: ???
  action_dim: ???
  feature_dim: ${agent.feature_dim}
  hidden_dim: ${agent.hidden_dim}
