# @package agent
_target_: agent.proto.ProtoAgent
_recursive_: False

name: proto
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}

use_tb: ${use_tb}
use_wandb: ${use_wandb}

init_actor: True
init_critic: true
init_critic_mode: 'only_trunk'
update_encoder: ${update_encoder}
grad_critic_params: null
optional_inits_args: null

base_optim_cfg:
  _target_: torch.optim.Adam
  lr: 1e-4
actor_optim_cfg:
  _target_: ${agent.base_optim_cfg._target_}
  lr: ${agent.base_optim_cfg.lr}
critic_optim_cfg:
  _target_: ${agent.base_optim_cfg._target_}
  lr: ${agent.base_optim_cfg.lr}

update_every_steps: 2
num_critic_updates: 1
num_actor_updates: 1  # num actor updates per update step

critic_target_tau: 0.01
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 3
batch_size: 1024
pred_dim: 128
proj_dim: 512
num_protos: 512
tau: 0.1
topk: 3
queue_size: 2048
encoder_target_tau: 0.05
